[package]
name = "quickwit-metastore"
version = "0.1.0"
authors = ['Quickwit, Inc. <hello@quickwit.io>']
edition = "2018"
license = "AGPL-3.0-or-later" # For a commercial, license, contact hello@quickwit.io
description = "Quickwit's metastore"
repository = "https://github.com/quickwit-inc/quickwit"
homepage = "https://quickwit.io/"
documentation = "https://quickwit.io/docs/"


[dependencies]
anyhow = "1.0"
async-trait = "0.1"
quickwit-index-config = { version = "0.1.0", path = "../quickwit-index-config" }
quickwit-storage = { version = "0.1.0", path = "../quickwit-storage" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = {version="1.6", features=["full"]}
chrono = "0.4"


[dependencies.mockall]
version = "0.9"
optional = true

[dependencies.tempfile]
version = "3"
optional = true

[dev-dependencies]
mockall = '0.9'
tempfile = '3'
quickwit-storage = { version = "0.1.0", path = "../quickwit-storage", features=["testsuite"]}

[features]
testsuite = ["mockall", "tempfile"]
