name: dockerhub

on:
  release:
    types: [published]

jobs:
  docker:
    name: Build & push dockerhub image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/artifact-name
        with: 
          suffix: ''
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/quickwit-cli:latest, ${{ secrets.DOCKERHUB_USERNAME }}/quickwit-cli:${{ env.ASSET_VERSION }}
